apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: chat-app
spec:
  selector:
    app: login-service
  ports:
  - name: socket-port
    protocol: TCP
    port: 80       # Port trên dịch vụ (external port)
    targetPort: 9090  # Port trên các pod (internal port)
    nodePort: 30004
  - name: rmi-port
    protocol: TCP
    port: 90       # Port trên dịch vụ (external port)
    targetPort: 1099  # Port trên các pod (internal port)
    nodePort: 30005     # NodePort (30000-32767)
  type: NodePort     # Kiểu dịch vụ là NodePort

--- #service database
apiVersion: v1
kind: Service
metadata:
  name: loginservicedb
  namespace: chat-app
spec:
  selector:
    app: login-service-mysql
  ports:
    - port: 3306
  type: ClusterIP
